"""Curated histology catalog.

Each tissue:
  id, name, path (browser tree), summary, features,
  cats  - Wikimedia Commons category substrings that strongly identify the tissue
  kw    - keywords (word-start match; trailing '$' = whole word) searched in file title/description/categories
  neg   - keywords that disqualify an image for this tissue
  structures / groups / contains / categories - 3D anatomy targets (exact base names, tree group names,
            substrings of structure names, material categories)
"""


def T(id, name, path, summary, features, kw, cats=(), neg=(), structures=(), groups=(), contains=(), categories=(),
      query=None):
    return dict(id=id, name=name, path=path, summary=summary, features=list(features), kw=list(kw), cats=list(cats),
                neg=list(neg), structures=list(structures), groups=list(groups), contains=list(contains),
                categories=list(categories), query=query or name)


EPI = ["Basic tissues", "Epithelium"]
CT = ["Basic tissues", "Connective tissue"]
CART = ["Basic tissues", "Cartilage & bone"]
MUS = ["Basic tissues", "Muscle tissue"]
NERV = ["Nervous system"]
INT = ["Integumentary system"]
CV = ["Cardiovascular system"]
LYM = ["Lymphoid organs"]
RESP = ["Respiratory system"]
GI = ["Digestive system"]
GI_GL = ["Digestive system", "Accessory glands"]
URO = ["Urinary system"]
MALE = ["Reproductive system", "Male"]
FEM = ["Reproductive system", "Female"]
ENDO = ["Endocrine system"]
SENSE = ["Special senses"]

TISSUES = [
    # ------------------------------------------------------------------ epithelium
    T("simple_squamous", "Simple squamous epithelium", EPI,
      "A single layer of flattened cells specialised for diffusion, filtration and friction-free surfaces.",
      ["Flattened nuclei bulge into the lumen or cavity",
       "Endothelium lines vessels; mesothelium lines pleura, pericardium and peritoneum",
       "Also forms type I pneumocytes and the parietal layer of Bowman's capsule",
       "Very thin barrier (<1 µm) allows rapid gas exchange and filtration"],
      ["simple squamous", "mesothelium", "endothelium"]),
    T("simple_cuboidal", "Simple cuboidal epithelium", EPI,
      "One layer of cube-shaped cells with round central nuclei, specialised for secretion and absorption.",
      ["Found in kidney tubules, thyroid follicles and small gland ducts",
       "Covers the ovary (surface epithelium) and forms the choroid plexus epithelium",
       "Apical microvilli in the proximal convoluted tubule increase absorptive area"],
      ["simple cuboidal"]),
    T("simple_columnar", "Simple columnar epithelium", EPI,
      "Tall cells with basal oval nuclei lining the stomach, intestines and gallbladder.",
      ["Absorptive enterocytes carry a microvillous brush border",
       "Goblet cells interspersed in intestine (absent from stomach surface)",
       "Ciliated variant lines the uterine tube",
       "Tight junctions near the apex create a selective barrier"],
      ["simple columnar"]),
    T("pseudostratified", "Pseudostratified ciliated columnar epithelium", EPI,
      "Respiratory epithelium: every cell touches the basement membrane but nuclei sit at different heights.",
      ["Motile cilia beat mucus toward the pharynx (mucociliary escalator)",
       "Goblet cells secrete mucus; basal cells are stem cells",
       "Lines nasal cavity, trachea and bronchi",
       "Stereocilia (long microvilli) variant lines the epididymis and ductus deferens",
       "Smoking causes squamous metaplasia, losing cilia"],
      ["pseudostratified", "respiratory epithelium"]),
    T("strat_squamous_nk", "Stratified squamous epithelium (non-keratinised)", EPI,
      "Multiple cell layers resisting abrasion on moist surfaces; superficial cells remain nucleated.",
      ["Basal layer of cuboidal stem cells on the basement membrane",
       "Lines oral cavity, oropharynx, oesophagus, vagina, ectocervix and anal canal",
       "Covers the cornea and conjunctiva",
       "Glycogen-rich cells in vagina appear clear"],
      ["non-keratinized", "nonkeratinized", "non-keratinised", "stratified squamous"], neg=["keratinized skin"]),
    T("strat_squamous_k", "Stratified squamous epithelium (keratinised)", EPI,
      "The epidermis: layers mature into anucleate keratin-filled squames that waterproof the body.",
      ["Strata basale, spinosum, granulosum, (lucidum) and corneum",
       "Keratohyalin granules in stratum granulosum",
       "Desmosomes give the 'prickle cell' look to stratum spinosum",
       "Turnover from basal layer to shedding takes about 4 weeks"],
      ["keratinized stratified", "keratinised stratified", "keratinized squamous", "orthokeratin"]),
    T("transitional", "Transitional epithelium (urothelium)", EPI,
      "Stretchable stratified epithelium unique to the urinary tract.",
      ["Large dome-shaped umbrella cells, sometimes binucleate, on the surface",
       "Uroplakin plaques make the apical membrane impermeable to urine",
       "Flattens from 6–7 layers to 2–3 layers when the bladder distends",
       "Lines renal calyces, pelvis, ureter, bladder and proximal urethra"],
      ["transitional epithelium", "urothelium", "urothelial"], cats=["histology of urothelium"]),
    T("strat_cub_col", "Stratified cuboidal & columnar epithelium", EPI,
      "Uncommon two-layered epithelia found mainly in large gland ducts.",
      ["Stratified cuboidal: ducts of sweat glands",
       "Stratified columnar: large salivary ducts, conjunctiva, parts of male urethra",
       "Often transitional zones between other epithelia"],
      ["stratified cuboidal", "stratified columnar"]),

    # ------------------------------------------------------------------ connective tissue
    T("loose_ct", "Loose (areolar) connective tissue", CT,
      "Cell-rich tissue with loosely arranged fibres and abundant ground substance.",
      ["Fibroblasts, macrophages, mast cells, plasma cells and leukocytes",
       "Thin collagen and elastic fibres in a hydrated ground substance",
       "Forms lamina propria under epithelia and surrounds vessels and nerves",
       "Site of oedema and of the early inflammatory response"],
      ["loose connective", "areolar"], cats=["areolar histology"]),
    T("dense_regular", "Dense regular connective tissue", CT,
      "Parallel bundles of type I collagen giving great tensile strength in one direction.",
      ["Rows of flattened fibroblast (tenocyte) nuclei between collagen bundles",
       "Crimped (wavy) collagen straightens under load",
       "Forms tendons, ligaments and aponeuroses",
       "Poor blood supply explains slow tendon healing"],
      ["dense regular", "tendon$", "tendons$", "aponeurosis", "ligament$"], cats=["histology of tendon", "histology of aponeurosis"],
      categories=["tendon", "ligament", "fascia", "capsule"]),
    T("dense_irregular", "Dense irregular connective tissue", CT,
      "Collagen bundles running in many directions to resist stress from all sides.",
      ["Reticular dermis of skin",
       "Capsules of organs, periosteum, perichondrium and dura mater",
       "Few cells; mostly type I collagen"],
      ["dense irregular"]),
    T("adipose", "Adipose tissue", CT,
      "Fat-storing connective tissue: white (unilocular) and brown (multilocular).",
      ["White adipocytes: one large lipid droplet pushes the nucleus to the rim ('signet ring')",
       "Lipid is dissolved during processing, leaving empty-looking cells",
       "Brown fat: many small droplets and mitochondria with UCP1 for heat (neonates)",
       "Richly vascularised; secretes leptin and adiponectin"],
      ["adipose", "adipocyte", "fat tissue", "brown fat", "white fat"], categories=["fat"]),
    T("reticular_ct", "Reticular connective tissue", CT,
      "A fine meshwork of type III collagen forming the scaffold of lymphoid and haematopoietic organs.",
      ["Reticular fibres are argyrophilic (black with silver stains)",
       "Produced by reticular cells (specialised fibroblasts)",
       "Stroma of lymph nodes, spleen, bone marrow and liver"],
      ["reticular fiber", "reticular fibre", "reticulin", "reticular connective", "reticular tissue"]),
    T("hyaline_cartilage", "Hyaline cartilage", CART,
      "Glassy, avascular cartilage of type II collagen: articular surfaces, costal cartilage, airways and growth plates.",
      ["Chondrocytes sit in lacunae, often as isogenous groups",
       "Basophilic territorial matrix rich in aggrecan around each group",
       "Perichondrium (except articular cartilage) supplies growth and nutrition",
       "Avascular, so nutrients diffuse through matrix; repairs poorly"],
      ["hyaline cartilage", "cartilage$"], cats=["histology of hyaline cartilage", "histology of cartilage"],
      neg=["elastic cartilage", "fibrocartilage"], categories=["cartilage"]),
    T("elastic_cartilage", "Elastic cartilage", CART,
      "Cartilage with a dense network of elastic fibres: flexible and recoils to shape.",
      ["Elastic fibres stain dark with orcein or Verhoeff stains",
       "Has a perichondrium like hyaline cartilage",
       "Auricle of the ear, epiglottis, external acoustic meatus, auditory tube"],
      ["elastic cartilage"], structures=["Epiglottis", "Helix", "Antihelix", "Tragus", "Antitragus", "Concha of auricle"],
      groups=["External ear"]),
    T("fibrocartilage", "Fibrocartilage", CART,
      "Rows of chondrocytes between thick type I collagen bundles, resisting compression and tension.",
      ["No perichondrium",
       "Intervertebral disc annulus fibrosus, pubic symphysis, menisci, labra, TMJ disc",
       "Transitional tissue where tendons insert into bone (enthesis)"],
      ["fibrocartilage", "intervertebral disc", "meniscus"], contains=["meniscus", "labrum", "intervertebral disc",
                                                                         "symphysis"]),
    T("compact_bone", "Compact (cortical) bone", CART,
      "Dense bone organised into osteons around central (Haversian) canals.",
      ["Concentric lamellae around a central canal with vessels and nerves",
       "Osteocytes in lacunae connected by canaliculi",
       "Perforating (Volkmann) canals link central canals",
       "Circumferential and interstitial lamellae fill between osteons",
       "Periosteum anchored by Sharpey fibres"],
      ["compact bone", "osteon", "haversian", "cortical bone", "ground bone", "bone$"],
      cats=["histology of bones", "histology of human bones"], neg=["marrow", "cancellous", "spongy"],
      categories=["bone"]),
    T("spongy_bone", "Spongy (cancellous) bone", CART,
      "A lattice of trabeculae aligned with lines of stress, with marrow in between.",
      ["Trabeculae lack osteons; nourished from marrow spaces",
       "Osteoblasts line forming surfaces; multinucleated osteoclasts sit in Howship lacunae",
       "Fills epiphyses, vertebral bodies and flat bones (diploë)",
       "Loss of trabeculae causes osteoporotic vertebral fractures"],
      ["spongy bone", "cancellous", "trabecular bone", "trabecula"], categories=["bone"]),
    T("ossification", "Bone development & growth plate", CART,
      "Endochondral and intramembranous ossification and the epiphyseal growth plate.",
      ["Growth plate zones: resting, proliferative (stacked columns), hypertrophic, calcified, ossification",
       "Achondroplasia (FGFR3) impairs the proliferative zone",
       "Intramembranous ossification forms flat skull bones and the clavicle",
       "Primary centres in diaphysis; secondary centres in epiphyses"],
      ["ossification", "growth plate", "epiphyseal plate", "endochondral", "intramembranous", "osteoblast", "osteoclast"],
      cats=["histology of ossification"], categories=["bone"]),
    T("bone_marrow", "Bone marrow", CART,
      "Haematopoietic tissue between sinusoids within bone.",
      ["Cords of developing blood cells between wide sinusoids",
       "Megakaryocytes are the largest cells, releasing platelets into sinusoids",
       "Fat cells increase with age (yellow marrow)",
       "Adult red marrow persists in the axial skeleton and proximal femur/humerus"],
      ["bone marrow", "megakaryocyte", "hematopoie", "haematopoie"], categories=["bone"]),
    T("blood", "Blood cells", CT,
      "The formed elements of peripheral blood in a stained smear.",
      ["Erythrocytes: anucleate biconcave discs, ~7.5 µm (useful size reference)",
       "Neutrophils 40–70%: multilobed nucleus, fine granules",
       "Lymphocytes 20–40%: round dense nucleus, thin rim of cytoplasm",
       "Monocytes: kidney-shaped nucleus; become macrophages",
       "Eosinophils: bilobed nucleus with red granules; basophils: dark purple granules",
       "Platelets: 2–3 µm anucleate fragments"],
      ["blood smear", "peripheral blood", "neutrophil", "eosinophil", "basophil", "lymphocyte", "monocyte",
       "erythrocyte", "platelet", "red blood cell", "white blood cell"], cats=["micrographs of blood"]),

    # ------------------------------------------------------------------ muscle
    T("skeletal_muscle", "Skeletal muscle", MUS,
      "Long, multinucleated, cross-striated fibres under voluntary control.",
      ["Nuclei at the periphery of each fibre (central nuclei suggest pathology/regeneration)",
       "A bands (dark), I bands (light) and Z lines form sarcomeres",
       "Endomysium around fibres, perimysium around fascicles, epimysium around the muscle",
       "Satellite cells beneath the basal lamina allow limited regeneration",
       "Type I (slow, oxidative) and type II (fast, glycolytic) fibres intermix"],
      ["skeletal muscle", "striated muscle", "muscle fiber", "muscle fibre", "sarcomere"], cats=["histology of muscles"],
      neg=["cardiac", "smooth muscle", "myocardium"], categories=["muscle"]),
    T("cardiac_muscle", "Cardiac muscle (myocardium)", MUS,
      "Branched, striated cells joined end-to-end by intercalated discs.",
      ["One or two central nuclei with a pale perinuclear zone",
       "Intercalated discs contain gap junctions (electrical coupling) and desmosomes",
       "Rich capillary network; mitochondria ~35% of cell volume",
       "Minimal regeneration, so infarcts heal by fibrous scar",
       "Purkinje fibres: large pale conducting cells beneath the endocardium"],
      ["cardiac muscle", "myocardium", "cardiomyocyte", "heart muscle", "purkinje fiber", "purkinje fibre"],
      cats=["histology of heart", "micrographs of the heart"], groups=["Heart"], categories=["heart"]),
    T("smooth_muscle", "Smooth muscle", MUS,
      "Spindle-shaped non-striated cells with a single central nucleus.",
      ["Cigar-shaped nucleus that corkscrews when the cell contracts",
       "Actin–myosin anchored at dense bodies rather than Z lines",
       "Gap junctions allow coordinated waves (peristalsis)",
       "Walls of viscera, vessels, airways, uterus, arrector pili and iris"],
      ["smooth muscle", "leiomyocyte", "myometrium"], neg=["skeletal muscle", "cardiac"]),

    # ------------------------------------------------------------------ nervous
    T("peripheral_nerve", "Peripheral nerve", NERV,
      "Bundles of myelinated and unmyelinated axons wrapped in three connective-tissue sheaths.",
      ["Epineurium surrounds the whole nerve; perineurium each fascicle (blood–nerve barrier)",
       "Endoneurium surrounds individual axons and their Schwann cells",
       "Myelin appears as clear halos in H&E; stains black with osmium",
       "Nodes of Ranvier allow saltatory conduction",
       "Wallerian degeneration follows axonal transection"],
      ["peripheral nerve", "nerve fascicle", "perineurium", "epineurium", "endoneurium", "myelinated", "schwann",
       "nerve$", "nerves$"], cats=["histology of nerves"], neg=["optic nerve", "nerve cell"], categories=["nerve"]),
    T("ganglion", "Sensory & autonomic ganglia", NERV,
      "Clusters of neuronal cell bodies outside the CNS.",
      ["Dorsal root ganglion: large round pseudounipolar neurons ringed by satellite cells, no synapses",
       "Autonomic ganglia: smaller multipolar neurons with eccentric nuclei and synapses",
       "Nissl substance and a prominent nucleolus in each neuron"],
      ["dorsal root ganglion", "spinal ganglion", "sensory ganglion", "autonomic ganglion", "sympathetic ganglion",
       "ganglion$", "ganglia$"], groups=["Ganglia"], contains=["ganglion"]),
    T("spinal_cord", "Spinal cord", NERV,
      "Central grey matter shaped like an H surrounded by white-matter tracts.",
      ["Anterior horns contain large multipolar motor neurons (lost in ALS, polio, SMA)",
       "Posterior horns receive sensory input; substantia gelatinosa processes pain",
       "Lateral horns (T1–L2) hold preganglionic sympathetic neurons",
       "Central canal lined by ependyma",
       "Cervical and lumbar enlargements have the largest anterior horns"],
      ["spinal cord"], groups=["Spinal cord", "Grey matter of spinal cord", "White matter of spinal cord"]),
    T("cerebral_cortex", "Cerebral cortex", NERV,
      "Six-layered neocortex of pyramidal and granular neurons.",
      ["Layers: I molecular, II external granular, III external pyramidal, IV internal granular, "
       "V internal pyramidal, VI multiform",
       "Primary motor cortex has giant Betz cells in layer V",
       "Primary visual cortex has a thick layer IV (stria of Gennari)",
       "Astrocytes, oligodendrocytes and microglia form the neuropil"],
      ["cerebral cortex", "neocortex", "pyramidal neuron", "pyramidal cell", "cortical layers", "cerebrum",
       "grey matter", "gray matter", "white matter", "neuron$", "neurons$", "astrocyte", "oligodendrocyte"],
      cats=["histology of telencephalon", "histology of prosencephalon", "brain histology", "micrographs of the brain"],
      neg=["cerebellum", "cerebellar", "hippocamp", "spinal cord"],
      groups=["Cerebrum", "Telencephalon", "Frontal lobe", "Parietal lobe", "Temporal lobe", "Occipital lobe",
              "Limbic lobe", "Insula"], categories=["brain", "white_matter"]),
    T("cerebellum", "Cerebellum", NERV,
      "Folded cortex with three layers around white-matter cores (arbor vitae).",
      ["Molecular layer: stellate and basket cells, Purkinje dendrites",
       "Purkinje cell layer: single row of large flask-shaped neurons – the only output (GABA)",
       "Granular layer: densely packed tiny granule cells",
       "Deep nuclei (dentate etc.) relay Purkinje output"],
      ["cerebellum", "cerebellar", "purkinje cell"], cats=["histology of the cerebellum"], groups=["Cerebellum"]),
    T("hippocampus", "Hippocampus", NERV,
      "Three-layered archicortex essential for forming new memories.",
      ["Cornu ammonis CA1–CA4 pyramidal layer and the dentate gyrus granule cells",
       "CA1 (Sommer sector) is most vulnerable to hypoxia",
       "Early site of neurofibrillary tangles in Alzheimer disease",
       "Mesial temporal sclerosis causes temporal lobe epilepsy"],
      ["hippocampus", "hippocampal", "dentate gyrus"], cats=["histology of hippocampus", "histology of human hippocampus"],
      contains=["hippocamp", "dentate", "fimbria"]),
    T("brainstem_bg", "Brainstem & basal ganglia", NERV,
      "Nuclei of the brainstem and deep grey matter, including pigmented neurons.",
      ["Substantia nigra and locus coeruleus neurons contain neuromelanin",
       "Loss of nigral neurons and Lewy bodies characterise Parkinson disease",
       "Striatum (caudate + putamen) is atrophied in Huntington disease",
       "Cranial nerve nuclei are clusters of large multipolar neurons"],
      ["basal ganglia", "putamen", "caudate", "substantia nigra", "locus coeruleus", "brainstem", "pons$",
       "medulla oblongata", "midbrain", "thalamus"],
      cats=["histology of basal ganglia", "histology of putamen", "histology of brainstem", "histology of pons",
            "locus coeruleus histology"], groups=["Brainstem", "Corpus striatum", "Midbrain", "Diencephalon"],
      contains=["nucleus", "nuclei"], categories=["nucleus"]),
    T("meninges_cp", "Meninges & choroid plexus", NERV,
      "Coverings of the CNS and the CSF-secreting choroid plexus.",
      ["Dura: dense fibrous tissue; arachnoid: delicate trabeculae over the subarachnoid space; pia on the brain",
       "Choroid plexus: fenestrated capillaries covered by cuboidal ependymal epithelium with microvilli",
       "Tight junctions between choroid epithelial cells form the blood–CSF barrier",
       "Arachnoid cap cells give rise to meningiomas (psammoma bodies)"],
      ["choroid plexus", "ependyma", "meninges", "dura mater", "arachnoid", "pia mater"],
      structures=["Choroid plexus"], groups=["Meninges", "Dura", "Leptomeninges", "Cranial dura", "Pia", "Cranial pia"]),

    # ------------------------------------------------------------------ integument
    T("thin_skin", "Thin (hairy) skin", INT,
      "Epidermis without a stratum lucidum over a dermis containing hair follicles and glands.",
      ["Thin stratum corneum; no stratum lucidum",
       "Hair follicles with sebaceous glands and arrector pili muscles",
       "Papillary dermis (loose) over reticular dermis (dense irregular)",
       "Melanocytes in the basal layer transfer melanin to keratinocytes",
       "Hypodermis of adipose tissue beneath"],
      ["skin$", "epidermis", "dermis", "cutaneous"], cats=["histology of skin", "histology of human skin",
                                                          "micrographs of the skin"],
      neg=["thick skin", "palm", "sole$", "plantar", "palmar", "fingertip", "scalp", "nail"], categories=["skin"]),
    T("thick_skin", "Thick (glabrous) skin", INT,
      "Hairless skin of palms and soles with a very thick keratin layer.",
      ["Thick stratum corneum and a distinct stratum lucidum",
       "No hair follicles or sebaceous glands",
       "Numerous eccrine sweat glands; ducts spiral through the epidermis",
       "Meissner corpuscles in dermal papillae; dermal ridges form fingerprints"],
      ["thick skin", "glabrous skin", "stratum lucidum", "palm$", "sole$", "plantar skin", "palmar skin", "fingertip",
       "acral skin"],
      structures=["Palm", "Sole", "Heel region", "Palmar surfaces of digits of hand", "Plantar surfaces of digits of foot",
                  "Hallucial eminence"]),
    T("hair_follicle", "Hair follicle & sebaceous gland", INT,
      "Epidermal down-growths producing hair, with attached sebaceous glands and arrector pili.",
      ["Hair bulb with matrix cells capping the dermal papilla",
       "Inner and outer root sheaths surround the hair shaft",
       "Sebaceous glands secrete holocrine sebum into the follicle",
       "Arrector pili smooth muscle erects the hair ('goose bumps')",
       "Bulge region holds follicular stem cells"],
      ["hair follicle", "scalp", "sebaceous", "arrector pili", "hair bulb", "hair shaft"],
      structures=["Hairs of head", "Eyebrow", "Eyelashes", "Pubic hairs", "Hairs of eyebrow"],
      groups=["Hairs", "Regions of epicranium"]),
    T("sweat_glands", "Sweat glands", INT,
      "Eccrine glands for thermoregulation and apocrine glands in the axilla and groin.",
      ["Eccrine: coiled secretory tubule of clear and dark cells with myoepithelial cells",
       "Eccrine duct: two layers of cuboidal cells, stains darker than the secretory coil",
       "Apocrine: wide lumens, decapitation secretion, open into hair follicles",
       "Cystic fibrosis raises sweat chloride (CFTR defect in the duct)"],
      ["sweat gland", "eccrine", "apocrine"], categories=["skin"]),
    T("skin_receptors", "Skin sensory receptors", INT,
      "Encapsulated mechanoreceptors of the dermis and hypodermis.",
      ["Meissner corpuscles: stacked lamellar cells in dermal papillae of glabrous skin (light touch)",
       "Pacinian (lamellar) corpuscles: onion-like capsules deep in dermis/hypodermis (vibration)",
       "Ruffini endings sense stretch; Merkel cells in the basal layer sense sustained pressure"],
      ["meissner", "pacinian", "lamellar corpuscle", "ruffini", "merkel cell", "mechanoreceptor"], categories=["skin"]),
    T("nail", "Nail", INT,
      "A plate of hard keratin produced by the nail matrix.",
      ["Nail matrix beneath the proximal nail fold generates the plate",
       "Nail bed epidermis lacks a granular layer",
       "Lunula is the visible distal matrix",
       "Eponychium (cuticle) seals the proximal fold"],
      ["nail$", "nail bed", "nail matrix", "nail plate"],
      structures=["Nail plate", "Nail plate (foot)", "Perionyx", "Perionyx (foot)"]),
    T("mammary", "Mammary gland", INT,
      "Branched tubuloalveolar gland organised into terminal duct lobular units.",
      ["TDLU: terminal duct plus acini, the site of most breast cancers",
       "Two-cell layer: luminal epithelial cells and outer myoepithelial cells",
       "Loose hormone-responsive intralobular stroma vs dense interlobular stroma",
       "Lactation: distended alveoli filled with lipid-rich secretion"],
      ["breast$", "mammary"], cats=["normal breast histology", "micrographs of the breast"],
      structures=["Mammary region", "Inframammary region"]),

    # ------------------------------------------------------------------ cardiovascular
    T("elastic_artery", "Elastic artery (aorta)", CV,
      "Large conducting arteries whose media is dominated by elastic lamellae.",
      ["Tunica media: 40–70 fenestrated elastic lamellae with smooth muscle between",
       "Stores energy in systole and recoils in diastole (Windkessel effect)",
       "Vasa vasorum supply the outer wall",
       "Cystic medial degeneration (Marfan) predisposes to aneurysm and dissection",
       "Tertiary syphilis destroys vasa vasorum → ascending aortic aneurysm"],
      ["aorta$", "aortic wall", "elastic artery", "elastic lamina", "elastic lamellae"], cats=["histology of aorta"],
      groups=["Aorta", "Root of aorta", "Aortic bifurcation"], contains=["aorta", "pulmonary trunk", "brachiocephalic trunk"]),
    T("muscular_artery", "Muscular arteries & arterioles", CV,
      "Distributing arteries with a thick smooth-muscle media and distinct elastic laminae.",
      ["Wavy internal elastic lamina beneath the endothelium",
       "Media of many circular smooth-muscle layers; external elastic lamina at its edge",
       "Arterioles (1–2 muscle layers) are the main site of vascular resistance",
       "Hyaline arteriolosclerosis in hypertension and diabetes",
       "Atherosclerotic plaques form in the intima"],
      ["muscular artery", "artery$", "arteries$", "arteriole"], cats=["histology of arteries"],
      neg=["aorta", "pulmonary"], categories=["artery"]),
    T("vein", "Veins & venules", CV,
      "Capacitance vessels with thin media, thick adventitia and (in limbs) valves.",
      ["Large, often collapsed lumen compared with the paired artery",
       "Thin media; adventitia is the thickest layer",
       "Valves: folds of intima prevent backflow (incompetence → varicose veins)",
       "Post-capillary venules are where leukocytes emigrate in inflammation"],
      ["vein$", "veins$", "venule", "venous"], cats=["histology of veins"], categories=["vein", "pulm_vein"]),
    T("capillaries", "Capillaries & sinusoids", CV,
      "Exchange vessels formed by endothelium and basal lamina.",
      ["Continuous capillaries: muscle, lung, CNS (blood–brain barrier)",
       "Fenestrated: kidney glomeruli, endocrine glands, intestinal villi",
       "Sinusoidal (discontinuous): liver, spleen, bone marrow",
       "Pericytes wrap capillaries and regulate flow"],
      ["capillary", "capillaries", "sinusoid", "fenestrated"], cats=["histology of skin capillaries"]),
    T("heart_valve", "Heart valves, endocardium & pericardium", CV,
      "Layered connective-tissue valves and the linings of the heart.",
      ["Valve cusps: fibrosa, spongiosa and ventricularis/atrialis layers; essentially avascular",
       "Endocardium: endothelium over subendothelial connective tissue",
       "Epicardium (visceral pericardium): mesothelium over fat containing coronary vessels",
       "Rheumatic fever causes Aschoff bodies and scarred, fused commissures"],
      ["heart valve", "cardiac valve", "endocardium", "epicardium", "pericardium", "chordae tendineae", "mitral valve",
       "aortic valve"],
      groups=["Valvular complex of heart", "Aortic valve", "Pulmonary valve", "Right atrioventricular valve"],
      contains=["leaflet", "papillary muscle"]),

    # ------------------------------------------------------------------ lymphoid
    T("lymph_node", "Lymph node", LYM,
      "Encapsulated filter of lymph organised into cortex, paracortex and medulla.",
      ["Afferent lymphatics pierce the capsule into the subcapsular sinus",
       "Cortex: B-cell follicles with germinal centres",
       "Paracortex: T cells and high endothelial venules (lymphocyte entry)",
       "Medulla: medullary cords of plasma cells and medullary sinuses to the hilum",
       "Sentinel node biopsy stages breast cancer and melanoma"],
      ["lymph node", "lymph nodes", "germinal center", "germinal centre", "lymphoid follicle"],
      cats=["histology of lymph"], neg=["metastas", "lymphoma"], categories=["lymph"]),
    T("spleen", "Spleen", LYM,
      "Blood filter of white pulp (immune) and red pulp (erythrocyte removal).",
      ["White pulp: PALS of T cells around central arterioles plus B-cell follicles",
       "Marginal zone at the white–red pulp interface traps blood-borne antigens",
       "Red pulp: splenic cords (of Billroth) and sinusoids with stave-like endothelium",
       "Asplenia predisposes to infection by encapsulated bacteria"],
      ["spleen", "splenic"], cats=["histology of spleen", "histology of human spleen"], structures=["Spleen"]),
    T("thymus", "Thymus", LYM,
      "Primary lymphoid organ where T cells mature, divided into lobules.",
      ["Dark cortex packed with thymocytes; paler medulla",
       "Hassall (thymic) corpuscles: whorls of epithelial reticular cells in the medulla",
       "No lymphoid follicles in the normal thymus",
       "Involutes and is replaced by fat after puberty",
       "DiGeorge syndrome: thymic aplasia from 3rd/4th pharyngeal pouch failure"],
      ["thymus", "thymic", "hassall"], cats=["histology of thymus"],
      structures=["Left lobe of thymus", "Right lobe of thymus"], groups=["Thymus"]),
    T("tonsil", "Tonsils (Waldeyer's ring)", LYM,
      "Partially encapsulated lymphoid tissue beneath the pharyngeal epithelium.",
      ["Palatine tonsil: non-keratinised stratified squamous epithelium dipping into deep crypts",
       "Numerous lymphoid follicles with germinal centres",
       "Pharyngeal tonsil (adenoid): covered by respiratory epithelium",
       "Peritonsillar abscess forms between the capsule and superior constrictor"],
      ["tonsil", "adenoid", "waldeyer"], cats=["histology of the adenoids"], structures=["Palatine tonsil"],
      groups=["Pharyngeal lymphoid ring"]),

    # ------------------------------------------------------------------ respiratory
    T("nasal_mucosa", "Nasal & olfactory mucosa", RESP,
      "Respiratory mucosa warming and humidifying air, with an olfactory patch in the roof.",
      ["Respiratory region: pseudostratified ciliated epithelium with goblet cells",
       "Large venous plexuses (swell bodies) in the lamina propria",
       "Olfactory epithelium: bipolar olfactory neurons, sustentacular and basal cells",
       "Bowman glands wash odorants from the olfactory surface"],
      ["olfactory epithelium", "olfactory mucosa", "nasal mucosa", "nasal cavity", "nasal septum", "turbinate"],
      structures=["Mucosa of nasal cavity"], groups=["Nose"]),
    T("larynx", "Larynx & vocal folds", RESP,
      "Cartilaginous airway guarding the lower respiratory tract and producing voice.",
      ["True vocal fold: stratified squamous epithelium over the vocal ligament and vocalis muscle",
       "Reinke space (superficial lamina propria) swells in Reinke oedema",
       "Vestibular (false) folds: respiratory epithelium with seromucous glands",
       "Epiglottis has an elastic cartilage core"],
      ["larynx", "laryngeal", "vocal fold", "vocal cord", "epiglottis"], groups=["Larynx"], structures=["Epiglottis"]),
    T("trachea", "Trachea", RESP,
      "Airway tube held open by C-shaped hyaline cartilage rings.",
      ["Pseudostratified ciliated columnar epithelium with goblet cells",
       "Thick basement membrane (thickened in asthma)",
       "Seromucous glands in the submucosa",
       "C-shaped hyaline cartilage rings; trachealis smooth muscle posteriorly"],
      ["trachea", "tracheal"], cats=["histology of trachea"], structures=["Trachea"]),
    T("bronchus", "Bronchi", RESP,
      "Intrapulmonary airways with cartilage plates and spirally arranged smooth muscle.",
      ["Irregular plates of hyaline cartilage replace the C-shaped rings",
       "Spiral bands of smooth muscle between mucosa and cartilage",
       "Submucosal glands and bronchus-associated lymphoid tissue",
       "Chronic bronchitis: gland hypertrophy (raised Reid index)"],
      ["bronchus", "bronchi$", "bronchial"], cats=["histology of bronchi"], neg=["bronchiole"],
      groups=["Bronchi", "Tracheobronchial tree"], contains=["bronchus"]),
    T("bronchiole", "Bronchioles", RESP,
      "Small airways without cartilage or glands, controlled by smooth muscle.",
      ["No cartilage and no submucosal glands",
       "Relatively thick smooth muscle – the site of bronchoconstriction in asthma",
       "Club (Clara) cells secrete surfactant-like proteins and detoxify",
       "Terminal bronchioles lead into respiratory bronchioles with alveoli in their walls"],
      ["bronchiole", "bronchioles", "club cell", "clara cell"], groups=["Lungs", "Left lung", "Right lung"]),
    T("lung", "Lung alveoli", RESP,
      "Gas-exchange surface of about 70 m² formed by millions of alveoli.",
      ["Type I pneumocytes (thin, ~95% of surface) form the air–blood barrier",
       "Type II pneumocytes secrete surfactant and regenerate the epithelium",
       "Alveolar macrophages ('dust cells'; haemosiderin-laden in heart failure)",
       "Air–blood barrier ~0.5 µm: epithelium, fused basement membranes, endothelium",
       "Pores of Kohn connect neighbouring alveoli"],
      ["lung$", "lungs$", "alveol", "pneumocyte", "pulmonary"], cats=["histology of lungs", "micrographs of the lung"],
      neg=["pulmonary artery", "pulmonary vein"], groups=["Lungs", "Left lung", "Right lung"],
      contains=["lobe of left lung", "lobe of right lung"], categories=["lung"]),
    T("serosa", "Pleura & peritoneum (serous membranes)", RESP,
      "Mesothelium on loose connective tissue lining body cavities and covering organs.",
      ["Simple squamous mesothelium produces lubricating serous fluid",
       "Visceral and parietal layers enclose a potential space",
       "Asbestos exposure causes pleural plaques and malignant mesothelioma",
       "Omentum contains milky spots of immune cells"],
      ["pleura", "peritoneum", "mesothelium", "mesothelial", "omentum", "serosa", "mesentery"],
      cats=["histology of pleura", "histology of peritoneum"],
      structures=["Pleura", "Greater omentum", "Lesser omentum", "Mesocolon", "Meso-appendix"], categories=["serosa"]),

    # ------------------------------------------------------------------ digestive tract
    T("oral_mucosa", "Lip & oral mucosa", GI,
      "Transition from skin to vermilion border to moist oral mucosa.",
      ["Skin side: hair follicles, sebaceous and sweat glands",
       "Vermilion: thin keratinised epithelium with tall papillae bringing capillaries close (red colour)",
       "Mucosal side: non-keratinised stratified squamous with minor salivary glands",
       "Gingiva and hard palate: masticatory keratinised mucosa bound to bone"],
      ["lip$", "lips$", "oral mucosa", "buccal mucosa", "gingiva", "gum$", "hard palate", "soft palate"],
      structures=["Gingiva", "Soft palate", "Uvula of palate", "Philtrum", "Tubercle of upper lip", "Labial commissure",
                  "Oral region"], groups=["Mouth"]),
    T("tongue", "Tongue & taste buds", GI,
      "Muscular organ covered by papillae, many bearing taste buds.",
      ["Filiform papillae: keratinised, no taste buds, most numerous",
       "Fungiform papillae: mushroom-shaped, with taste buds on top",
       "Circumvallate papillae: in a trench with taste buds and serous von Ebner glands",
       "Interlacing skeletal muscle fibres in three planes",
       "Taste buds: pale barrel-shaped clusters of gustatory and supporting cells"],
      ["tongue", "lingual", "filiform", "fungiform", "circumvallate", "vallate papilla", "taste bud"],
      cats=["histology of tongue"], structures=["Tongue"]),
    T("tooth", "Tooth", GI,
      "Mineralised tissues – enamel, dentin, cementum – around a vascular pulp.",
      ["Enamel: ~96% hydroxyapatite, acellular, made by ameloblasts (lost in decalcified sections)",
       "Dentin: dentinal tubules containing odontoblast processes",
       "Pulp: loose connective tissue with vessels and nerves",
       "Cementum and periodontal ligament anchor the root (gomphosis)",
       "Development: bud, cap and bell stages"],
      ["tooth", "teeth", "dentin", "dentine", "enamel", "dental pulp", "odontoblast", "periodontal", "cementum",
       "ameloblast", "tooth germ"], cats=["histology of teeth"], categories=["tooth"]),
    T("oesophagus", "Oesophagus", GI,
      "Muscular tube lined by non-keratinised stratified squamous epithelium.",
      ["Thick stratified squamous epithelium resists abrasion",
       "Submucosal oesophageal glands lubricate the lumen",
       "Muscularis externa: skeletal (upper third) → mixed → smooth (lower third)",
       "Adventitia rather than serosa above the diaphragm",
       "Submucosal venous plexus forms varices in portal hypertension"],
      ["esophag", "oesophag"], cats=["histology of the esophagus"], neg=["barrett", "junction"],
      structures=["Oesophagus"]),
    T("gej", "Gastro-oesophageal junction", GI,
      "Abrupt change from squamous oesophageal to columnar gastric mucosa (Z-line).",
      ["Squamous epithelium ends sharply at the Z-line",
       "Cardiac glands: coiled mucous glands of the proximal stomach",
       "Barrett oesophagus: intestinal metaplasia with goblet cells above the junction",
       "Lower oesophageal sphincter is physiological, not anatomical"],
      ["gastroesophageal junction", "gastro-oesophageal junction", "esophagogastric junction", "cardiac glands",
       "gastric cardia"], structures=["Oesophagus"]),
    T("stomach", "Stomach (fundus & body)", GI,
      "Acid-secreting mucosa of gastric pits and long oxyntic glands.",
      ["Surface mucous cells (simple columnar, no goblet cells) line shallow gastric pits",
       "Parietal cells: large eosinophilic cells secreting HCl and intrinsic factor",
       "Chief cells: basophilic cells at gland bases secreting pepsinogen",
       "Enterochromaffin-like cells release histamine",
       "Three-layer muscularis externa with an inner oblique layer",
       "Autoimmune gastritis destroys parietal cells → pernicious anaemia"],
      ["stomach", "gastric", "fundic", "oxyntic", "parietal cell", "chief cell"],
      cats=["histology of stomach"], neg=["pylor", "antrum", "antral", "gastric cardia", "junction"],
      structures=["Stomach", "Mucosa of stomach"]),
    T("pylorus", "Pyloric antrum", GI,
      "Distal stomach with deep pits, mucous glands and gastrin-producing G cells.",
      ["Pits occupy about half of the mucosal depth",
       "Short coiled mucous glands with G cells (gastrin)",
       "Thickened circular muscle forms the pyloric sphincter",
       "Hypertrophic pyloric stenosis causes projectile vomiting in infants"],
      ["pylor", "antrum", "antral"], structures=["Stomach"]),
    T("duodenum", "Duodenum", GI,
      "First part of the small intestine, identified by submucosal Brunner glands.",
      ["Leaf-shaped villi and crypts of Lieberkühn",
       "Brunner glands in the submucosa secrete alkaline mucus – diagnostic of duodenum",
       "Receives bile and pancreatic juice at the major duodenal papilla",
       "Coeliac disease: villous atrophy, crypt hyperplasia, intraepithelial lymphocytes"],
      ["duodenum", "duodenal", "brunner"], cats=["histology of the duodenum"], structures=["Duodenum"]),
    T("jejunum", "Jejunum", GI,
      "The main absorptive segment with tall villi and prominent circular folds.",
      ["Tall finger-like villi on high plicae circulares",
       "Enterocytes with brush border, goblet cells and Paneth cells in crypts",
       "No Brunner glands and few Peyer patches",
       "Rich lacteals in villus cores absorb fat"],
      ["jejunum", "jejunal", "small intestine", "villi", "villus", "paneth", "enterocyte"],
      cats=["histology of jejunum", "histology of intestines"], neg=["ileum", "colon", "duodenum"],
      structures=["Jejunum"], groups=["Small intestine"]),
    T("ileum", "Ileum", GI,
      "Distal small intestine with shorter villi, more goblet cells and Peyer patches.",
      ["Peyer patches: aggregated lymphoid follicles in mucosa and submucosa",
       "M cells over follicles sample luminal antigens",
       "Terminal ileum absorbs vitamin B12–intrinsic factor and bile acids",
       "Crohn disease favours the terminal ileum"],
      ["ileum", "ileal", "peyer"], cats=["histology of ileum"], groups=["Small intestine"]),
    T("colon", "Colon & rectum", GI,
      "Large intestine without villi, packed with goblet-cell-rich straight crypts.",
      ["No villi; straight tubular crypts of Lieberkühn",
       "Abundant goblet cells for lubrication; absorptive colonocytes reclaim water",
       "Outer longitudinal muscle gathered into three taeniae coli",
       "Fat-filled appendices epiploicae on the serosa",
       "Adenoma → carcinoma sequence arises in crypt epithelium"],
      ["colon$", "colonic", "large intestine", "rectum", "rectal", "colorectal"],
      cats=["histology of colon"], neg=["appendix"],
      structures=["Ascending colon", "Transverse colon", "Descending colon", "Sigmoid colon", "Free taenia",
                  "Mesocolic taenia", "Omental taenia"], groups=["Colon", "Large intestine", "Taeniae coli"],
      categories=["gut"]),
    T("appendix", "Vermiform appendix", GI,
      "Colonic-type mucosa with very abundant lymphoid tissue.",
      ["Irregular sparse crypts surrounded by lymphoid follicles",
       "Lymphoid tissue most prominent in children and young adults",
       "Complete outer longitudinal muscle layer where the taeniae converge",
       "Luminal obstruction (fecalith, lymphoid hyperplasia) causes appendicitis"],
      ["appendix", "appendiceal", "vermiform"], cats=["histology of appendix"],
      structures=["Vermiform appendix", "Meso-appendix"]),
    T("anal_canal", "Anal canal", GI,
      "Transition from colorectal mucosa to stratified squamous epithelium and skin.",
      ["Colorectal columnar mucosa above the anal transitional zone",
       "Non-keratinised stratified squamous below the pectinate line",
       "Keratinised skin with hair and apocrine glands at the anal verge",
       "Internal (smooth) and external (skeletal) sphincters; haemorrhoidal venous plexus"],
      ["anal canal", "anorectal", "anal transition", "pectinate line", "anus$"], structures=["Anal region"]),

    # ------------------------------------------------------------------ digestive glands
    T("parotid", "Parotid gland", GI_GL,
      "Purely serous salivary gland producing watery, amylase-rich saliva.",
      ["Serous acini with basal basophilia and apical zymogen granules",
       "Prominent intercalated and striated ducts",
       "Adipocytes increase with age",
       "Facial nerve branches run through the gland"],
      ["parotid"], structures=["Parotid gland", "Accessory parotid gland", "Parotid duct"]),
    T("submandibular", "Submandibular gland", GI_GL,
      "Mixed gland, mostly serous, with serous demilunes capping mucous acini.",
      ["Predominantly serous acini with scattered mucous acini",
       "Serous demilunes (partly a fixation artefact) on mucous tubules",
       "Long striated ducts",
       "Most common site of salivary stones (sialolithiasis)"],
      ["submandibular", "submaxillary", "serous demilune"], structures=["Submandibular gland", "Submandibular duct"]),
    T("sublingual", "Sublingual gland", GI_GL,
      "Mixed gland dominated by pale-staining mucous acini.",
      ["Mostly mucous acini with flattened basal nuclei",
       "Few serous demilunes",
       "Short, inconspicuous striated ducts",
       "Ranula: mucus extravasation cyst of the floor of mouth"],
      ["sublingual"], structures=["Sublingual gland"]),
    T("liver", "Liver", GI_GL,
      "Plates of hepatocytes between sinusoids, organised around central veins and portal triads.",
      ["Classic lobule: central vein with radiating hepatocyte plates",
       "Portal triad: portal vein, hepatic artery and bile ductule",
       "Sinusoids lined by fenestrated endothelium and Kupffer cells",
       "Space of Disse contains stellate (Ito) cells – fibrosis in cirrhosis",
       "Zone 3 (centrilobular) is most susceptible to hypoxia and paracetamol toxicity"],
      ["liver", "hepatic", "hepatocyte", "portal triad", "kupffer", "hepatic lobule"],
      cats=["histology of liver", "micrographs of the liver"], neg=["hepatic artery", "hepatic vein"],
      structures=["Liver"], contains=["segment of liver"]),
    T("gallbladder", "Gallbladder & bile ducts", GI_GL,
      "Folded simple columnar mucosa that concentrates bile.",
      ["Tall simple columnar epithelium, no goblet cells",
       "No muscularis mucosae and no submucosa",
       "Rokitansky–Aschoff sinuses: mucosal herniations through the muscle",
       "Cholesterol stones form when bile is supersaturated"],
      ["gallbladder", "gall bladder", "bile duct", "biliary"], cats=["histology of gallbladder"],
      structures=["Gallbladder", "Bile duct"], groups=["Extrahepatic bile ducts"], categories=["biliary"]),
    T("pancreas", "Exocrine pancreas", GI_GL,
      "Serous acini secreting digestive enzymes, with scattered endocrine islets.",
      ["Acinar cells: basal basophilia, apical eosinophilic zymogen granules",
       "Centroacinar cells secrete bicarbonate (pale cells within acini)",
       "No striated ducts (distinguishes it from parotid)",
       "Trypsin activation within the gland causes acute pancreatitis"],
      ["pancreas", "pancreatic", "acinar cell", "centroacinar"],
      cats=["histology of pancreas", "micrographs of the pancreas"], neg=["islet", "langerhans"],
      structures=["Pancreas", "Pancreatic duct", "Accessory pancreatic duct"]),
    T("islets", "Pancreatic islets of Langerhans", ENDO,
      "Pale endocrine clusters within the exocrine pancreas.",
      ["β cells (~65%, central) secrete insulin; α cells (glucagon) at the periphery",
       "δ cells secrete somatostatin; PP cells pancreatic polypeptide",
       "Dense fenestrated capillary network",
       "Type 1 diabetes: autoimmune insulitis; type 2: islet amyloid (amylin)"],
      ["islet", "islets", "langerhans", "beta cell", "alpha cell"], structures=["Pancreas"]),

    # ------------------------------------------------------------------ urinary
    T("kidney_cortex", "Kidney cortex & glomerulus", URO,
      "Renal corpuscles and convoluted tubules of the nephron.",
      ["Renal corpuscle: glomerular capillary tuft inside Bowman capsule",
       "Proximal convoluted tubule: eosinophilic cells with brush border, fuzzy lumen",
       "Distal convoluted tubule: smaller paler cells with a clear lumen",
       "Macula densa and renin-secreting juxtaglomerular cells form the JG apparatus",
       "Podocyte foot processes and fenestrated endothelium form the filtration barrier"],
      ["kidney", "renal", "glomerul", "nephron", "bowman", "proximal tubule", "convoluted tubule", "macula densa",
       "juxtaglomerular", "podocyte"], cats=["histology of kidney", "micrographs of the kidney", "svg histology of kidney"],
      neg=["renal medulla", "renal pelvis", "collecting duct", "renal artery", "renal vein"], structures=["Kidney"]),
    T("kidney_medulla", "Kidney medulla & collecting system", URO,
      "Loops of Henle, collecting ducts and vasa recta concentrating urine.",
      ["Collecting ducts: cuboidal to columnar cells with distinct borders (principal & intercalated cells)",
       "Thin limbs of Henle resemble capillaries but lack blood cells",
       "Vasa recta countercurrent exchange preserves the medullary gradient",
       "Papillary ducts open onto the renal papilla into a minor calyx"],
      ["renal medulla", "collecting duct", "loop of henle", "renal papilla", "medullary ray", "renal pelvis"],
      structures=["Kidney", "Renal pelvis"]),
    T("ureter", "Ureter", URO,
      "Muscular tube with a star-shaped lumen lined by urothelium.",
      ["Folded mucosa gives a stellate lumen",
       "Inner longitudinal and outer circular smooth muscle (extra outer longitudinal layer distally)",
       "Peristalsis moves urine; stones lodge at the pelviureteric junction, pelvic brim and bladder wall"],
      ["ureter$", "ureters$", "ureteric"], cats=["histology of ureters"], structures=["Ureter"]),
    T("bladder", "Urinary bladder", URO,
      "Distensible reservoir of urothelium over a thick detrusor muscle.",
      ["Urothelium with umbrella cells; mucosal folds flatten when full",
       "Detrusor: interwoven bundles of smooth muscle",
       "Trigone mucosa is smooth and relatively fixed",
       "Urothelial carcinoma linked to smoking and aromatic amines"],
      ["urinary bladder", "bladder$", "detrusor"], cats=["micrographs of the urinary bladder"],
      neg=["gallbladder", "gall bladder"], structures=["Urinary bladder"]),
    T("urethra", "Urethra", URO,
      "Outflow tract whose lining changes from urothelium to stratified squamous epithelium.",
      ["Prostatic urethra: urothelium",
       "Membranous and spongy urethra: pseudostratified or stratified columnar",
       "Navicular fossa: stratified squamous",
       "Mucous glands of Littré along the spongy urethra"],
      ["urethra"], structures=["Urethra"]),

    # ------------------------------------------------------------------ male
    T("testis", "Testis", MALE,
      "Seminiferous tubules producing sperm, with androgen-secreting interstitial cells.",
      ["Sertoli cells: tall supporting cells with tight junctions forming the blood–testis barrier",
       "Germ cells mature from spermatogonia at the base to spermatids at the lumen",
       "Leydig cells in the interstitium secrete testosterone (Reinke crystals)",
       "Thick tunica albuginea capsule",
       "Cryptorchidism impairs spermatogenesis and raises cancer risk"],
      ["testis", "testes", "testicle", "testicular", "seminiferous", "sertoli", "leydig", "spermatogen"],
      structures=["Testis"]),
    T("epididymis", "Epididymis", MALE,
      "Highly coiled duct where sperm mature and are stored.",
      ["Pseudostratified columnar epithelium with long stereocilia",
       "Smooth, round lumen filled with sperm",
       "Thin circular smooth-muscle layer that thickens toward the tail"],
      ["epididymis", "epididymal"], cats=["histology of epididymis"], structures=["Epididymis"]),
    T("ductus_deferens", "Ductus deferens", MALE,
      "Narrow-lumen duct with a very thick three-layered muscular wall.",
      ["Pseudostratified columnar epithelium with stereocilia",
       "Inner longitudinal, middle circular, outer longitudinal smooth muscle",
       "Palpable in the spermatic cord; divided in vasectomy"],
      ["vas deferens", "ductus deferens", "deferent duct", "spermatic cord"],
      structures=["Ductus deferens", "Ejaculatory duct"]),
    T("seminal_vesicle", "Seminal vesicle", MALE,
      "Coiled gland with honeycomb mucosal folds secreting fructose-rich fluid.",
      ["Complex branching folds create a honeycomb pattern",
       "Pseudostratified or cuboidal epithelium, often with lipofuscin",
       "Eosinophilic secretion fills the lumen",
       "Provides ~70% of ejaculate volume"],
      ["seminal vesicle", "seminal gland", "vesicular gland"], structures=["Seminal gland"]),
    T("prostate", "Prostate", MALE,
      "Tubuloalveolar glands in a fibromuscular stroma surrounding the urethra.",
      ["Glands with papillary infoldings and a two-cell layer (secretory + basal)",
       "Corpora amylacea: laminated concretions in gland lumens",
       "Peripheral zone: most carcinomas (palpable on DRE)",
       "Transition zone: benign prostatic hyperplasia",
       "Loss of the basal cell layer is a hallmark of carcinoma"],
      ["prostate", "prostatic"], cats=["histology of prostate"], structures=["Prostate"]),
    T("penis", "Penis & erectile tissue", MALE,
      "Three erectile bodies of vascular spaces surrounded by tunica albuginea.",
      ["Corpora cavernosa: endothelium-lined cavernous spaces separated by smooth-muscle trabeculae",
       "Corpus spongiosum surrounds the spongy urethra",
       "Helicine arteries dilate via NO–cGMP during erection",
       "Thick tunica albuginea; Peyronie disease is fibrosis of it"],
      ["penis", "penile", "corpus cavernosum", "corpus spongiosum", "erectile tissue"],
      structures=["Corpus cavernosum of penis", "Corpus spongiosum of penis", "Glans penis"], groups=["Penis"]),

    # ------------------------------------------------------------------ female
    T("ovary", "Ovary", FEM,
      "Cortex of follicles at every stage around a vascular medulla.",
      ["Surface (germinal) epithelium over a dense tunica albuginea",
       "Primordial → primary → secondary → Graafian (antral) follicles",
       "Theca interna makes androgens; granulosa cells aromatise them to oestrogen",
       "Corpus luteum after ovulation; corpus albicans scar afterwards"],
      ["ovary", "ovarian", "ovarian follicle", "corpus luteum", "oocyte", "granulosa", "theca", "corpus albicans"],
      cats=["histology of the ovary"]),
    T("uterine_tube", "Uterine tube", FEM,
      "Oviduct with highly branched mucosal folds lined by ciliated and peg cells.",
      ["Ampulla has the most elaborate folds – usual site of fertilisation and ectopic pregnancy",
       "Ciliated cells move the oocyte; peg (secretory) cells nourish it",
       "Inner circular and outer longitudinal smooth muscle"],
      ["fallopian tube", "uterine tube", "oviduct", "salpinx", "fimbria"], neg=["hippocamp"]),
    T("uterus", "Uterus (endometrium & myometrium)", FEM,
      "Cyclical endometrium over a thick smooth-muscle myometrium.",
      ["Functional layer shed at menstruation; basal layer regenerates it",
       "Proliferative phase: straight tubular glands with mitoses",
       "Secretory phase: coiled glands, subnuclear vacuoles, stromal oedema",
       "Spiral arteries constrict before menstruation",
       "Leiomyomas (fibroids) arise from the myometrium"],
      ["uterus", "uterine", "endometri", "myometri", "perimetri"],
      cats=["histology of uterus", "histology of endometrium", "histology of myometrium", "histology of perimetrium"],
      neg=["decidua", "placenta", "uterine tube", "endometriosis"]),
    T("cervix", "Cervix", FEM,
      "Canal of mucus-secreting columnar epithelium meeting the squamous ectocervix.",
      ["Endocervix: simple columnar mucous epithelium in branching clefts",
       "Ectocervix: non-keratinised stratified squamous",
       "Transformation zone (squamocolumnar junction) is where HPV-related dysplasia arises",
       "Nabothian cysts: obstructed endocervical glands"],
      ["cervix", "cervical canal", "ectocervix", "endocervix", "transformation zone"], neg=["cervical vertebra", "spine"]),
    T("vagina", "Vagina", FEM,
      "Glandless muscular canal lined by glycogen-rich stratified squamous epithelium.",
      ["Non-keratinised stratified squamous epithelium rich in glycogen",
       "No glands – lubrication comes from cervical mucus and transudate",
       "Lamina propria rich in elastic fibres and thin-walled veins",
       "Lactobacilli ferment glycogen to keep the pH acidic"],
      ["vagina", "vaginal"]),
    T("placenta", "Placenta", FEM,
      "Fetal chorionic villi bathed in maternal blood.",
      ["Villi covered by syncytiotrophoblast (hCG) over cytotrophoblast",
       "Cytotrophoblast layer becomes discontinuous in later pregnancy",
       "Fetal capillaries and Hofbauer macrophages in the villous core",
       "Decidual cells of the maternal endometrium; placenta accreta if decidua is deficient"],
      ["placenta", "placental", "chorionic villi", "chorionic villus", "decidua", "syncytiotrophoblast",
       "cytotrophoblast", "umbilical cord"], cats=["histology of the placenta", "histology of decidua",
                                                  "histology of pregnancy"]),

    # ------------------------------------------------------------------ endocrine
    T("pituitary", "Pituitary gland", ENDO,
      "Glandular anterior lobe and neural posterior lobe.",
      ["Anterior lobe: acidophils (GH, prolactin), basophils (ACTH, TSH, FSH, LH), chromophobes",
       "Posterior lobe: unmyelinated axons, pituicytes and Herring bodies storing ADH and oxytocin",
       "Pars intermedia contains colloid-filled Rathke cysts",
       "Prolactinoma is the commonest functioning adenoma"],
      ["pituitary", "hypophys", "adenohypophys", "neurohypophys", "pars distalis", "pars nervosa", "herring bod"],
      structures=["Adenohypophysis", "Neurohypophysis"], groups=["Hypophysis"]),
    T("thyroid", "Thyroid gland", ENDO,
      "Follicles of cuboidal cells storing thyroglobulin colloid.",
      ["Follicles lined by simple cuboidal epithelium; height reflects activity",
       "Colloid shows resorption vacuoles at the edge when active",
       "Parafollicular C cells (calcitonin) between follicles",
       "Graves disease: tall hyperplastic cells with scalloped colloid",
       "Hashimoto thyroiditis: lymphoid follicles and Hürthle cells"],
      ["thyroid", "thyroid follicle", "colloid", "parafollicular"], cats=["histology of thyroid",
                                                                           "micrographs of the thyroid"],
      neg=["parathyroid", "thyroid cartilage"], structures=["Thyroid gland", "Isthmus of thyroid gland",
                                                             "Lobe of thyroid gland"]),
    T("parathyroid", "Parathyroid gland", ENDO,
      "Cords of chief cells secreting parathyroid hormone.",
      ["Chief cells in cords and nests with rich capillaries",
       "Oxyphil cells: larger, eosinophilic, mitochondria-rich; increase with age",
       "Adipocytes increase with age",
       "Adenoma of one gland causes most primary hyperparathyroidism"],
      ["parathyroid"], cats=["histology of parathyroid"],
      structures=["Superior parathyroid gland", "Inferior parathyroid gland"], groups=["Parathyroid glands"]),
    T("adrenal", "Adrenal (suprarenal) gland", ENDO,
      "Steroid-secreting cortex in three zones around a catecholamine-secreting medulla.",
      ["Zona glomerulosa: clusters of cells – aldosterone",
       "Zona fasciculata: cords of lipid-laden foamy spongiocytes – cortisol",
       "Zona reticularis: network of cells with lipofuscin – androgens",
       "Medulla: chromaffin cells (epinephrine, norepinephrine)",
       "Pheochromocytoma arises from medullary chromaffin cells"],
      ["adrenal", "suprarenal", "zona glomerulosa", "zona fasciculata", "zona reticularis", "chromaffin"],
      cats=["micrographs of the adrenal glands"], structures=["Suprarenal gland"]),
    T("pineal", "Pineal gland", ENDO,
      "Lobules of pinealocytes secreting melatonin, with calcified brain sand.",
      ["Pinealocytes with interstitial astrocytes in lobules",
       "Corpora arenacea (brain sand) calcify with age – a radiological landmark",
       "Melatonin secretion follows darkness via the retino-hypothalamic-sympathetic pathway",
       "Pineal tumours compress the tectum → Parinaud syndrome"],
      ["pineal"], cats=["histology of pineal gland"], structures=["Pineal gland"]),

    # ------------------------------------------------------------------ special senses
    T("cornea", "Cornea", SENSE,
      "Transparent, avascular front of the eye with a precisely ordered stroma.",
      ["Non-keratinised stratified squamous epithelium",
       "Bowman layer beneath the epithelium",
       "Stroma: orthogonal lamellae of uniform collagen fibrils ensure transparency",
       "Descemet membrane and a single-layer endothelium that pumps water out",
       "Endothelium does not regenerate – loss causes corneal oedema"],
      ["cornea", "corneal"], cats=["histology of the cornea"], structures=["Cornea"]),
    T("retina", "Retina", SENSE,
      "Ten-layered neural tissue converting light into nerve signals.",
      ["Pigment epithelium, photoreceptor segments, outer limiting membrane",
       "Outer nuclear layer (rods & cones), outer plexiform, inner nuclear, inner plexiform layers",
       "Ganglion cell layer, nerve fibre layer, inner limiting membrane",
       "Fovea: cones only, with inner layers pushed aside",
       "Retinal detachment separates the neural retina from the pigment epithelium"],
      ["retina", "retinal", "photoreceptor", "rods and cones", "fovea", "macula lutea"],
      cats=["histology of the retina"], structures=["Retina"]),
    T("eye", "Eyeball, lens & eyelid", SENSE,
      "Sclera, uvea, lens and eyelid structures of the eye.",
      ["Sclera: dense irregular connective tissue continuous with the cornea",
       "Ciliary body: ciliary muscle and processes secreting aqueous humour",
       "Iris: pigmented stroma with sphincter and dilator pupillae muscles",
       "Lens: capsule, anterior epithelium and anucleate lens fibres",
       "Eyelid: tarsal plate with meibomian glands, orbicularis oculi, conjunctiva"],
      ["eyeball", "sclera", "ciliary body", "iris$", "lens$", "eyelid", "conjunctiva", "lacrimal"],
      cats=["histology of the eye"], neg=["retina", "cornea", "compound eye"],
      structures=["Iris", "Lens", "Sclera", "Vitreous body", "Lacrimal gland", "Zonular fibres"],
      groups=["Eyeball", "Eye", "Lacrimal apparatus"], categories=["eye"]),
    T("ear", "Inner ear & cochlea", SENSE,
      "Membranous labyrinth with sensory hair cells for hearing and balance.",
      ["Cochlear duct (scala media) between scala vestibuli and scala tympani",
       "Organ of Corti: inner and outer hair cells on the basilar membrane under the tectorial membrane",
       "Stria vascularis secretes potassium-rich endolymph",
       "Maculae (utricle, saccule) with otoliths; cristae ampullares in semicircular canals",
       "Aminoglycosides and loud noise destroy outer hair cells"],
      ["cochlea", "cochlear", "organ of corti", "inner ear", "vestibular", "crista ampullaris", "tympanic membrane",
       "ear$"], cats=["histology of the ears"],
      structures=["Cochlea", "Vestibule", "Tympanic membrane"], groups=["Internal ear", "Middle ear", "Ear"]),
]
